---

- name: Install Asterisk requirements
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - asterisk
    - asterisk-mp3
    - libsox-fmt-mp3
  register: my_result
  until: my_result is succeeded
  tags: asterisk
